backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
site_url: "https://co-design.netlify.app"
media_folder: "src/assets/images"
public_folder: "/assets/images"
collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    create: true
    filter: {field: "editable", value: true}
    fields:
      - {label: "Editable", name: "editable", widget: hidden, default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - {label: "Banner Type", name: "banner", widget: "hidden"}
      - {label: "Banner Background", name: "bannerBg", widget: "hidden"}
      - {label: "Banner Text", name: "bannerText", widget: "hidden"}
      - {label: "Table of Contents", name: "toc", widget: "hidden", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: resources
    label: Resources
    label_singular: Resource
    folder: "src/resources"
    slug: "{{slug}}"
    preview_path: "resources/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - label: "Resource Type"
        name: "type"
        widget: "select"
        options: ["Guide", "Activity", "Tool"]
      - label: "Building Block"
        name: "buildingBlock"
        widget: "select"
        options: ["Partnership", "Community involvement", "Co-design plan", "Facilitation", "Ideas and outcomes", "Reflection"]
      - {label: "Body", name: "body", widget: "markdown"}
  - name: case-studies
    label: Case Studies
    label_singular: Case Study
    folder: "src/case-studies"
    slug: "{{slug}}"
    preview_path: "/case-studies/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Authors", name: "authors", widget: "list"}
      - {label: "Organization", name: "organization", widget: "string", required: false}
      - {label: "Start Year", name: "startDate", widget: "string", required: true}
      - {label: "End Year", name: "endDate", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
